
on: push
language: php
php:
  - '7.0'
  - '7.1'
jobs:
 
  build:

    runs-on:window-latest

    steps:
    - uses: actions/checkout@v2
     - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
script:
   - composer install
   - vendor/bin/phpunit
